from django.urls import path
from . import views

urlpatterns = [
    path("", views.login_page, name='loginpage'),
    path("Login/", views.Login, name='login'),
    path("Logout/", views.Logout, name='logout'),
    path("admin/home/", views.admin_home_page, name='admin_home_page'),
    path("add/class/", views.add_class, name='add_class'),
    path("manage/class/", views.manage_class, name='manage_class'),
    path("edit/class/<int:level_id>", views.edit_class, name='edit_class'),
    path("delete/class/<int:level_id>", views.delete_class, name='delete_class'),
    path("add/section/", views.add_section, name='add_section'),
    path("manage/section/", views.manage_section, name='manage_section'),
    path("edit/section/<int:section_id>", views.edit_section, name='edit_section'),
    path("delete/section/<int:section_id>", views.delete_section, name='delete_section'),
    path("add/session/", views.add_session, name='add_session'),
    path("manage/session/", views.manage_session, name='manage_session'),
    path("edit/session/<int:session_id>",views.edit_session, name='edit_session'),
    path("delete/session/<int:session_id>",views.delete_session, name='delete_session'),
    path("add/subject/",views.add_subject,name='add_subject'),
    path("manage/subject/", views.manage_subject, name='manage_subject'),
    path("edit/subject/<int:subject_id>", views.edit_subject, name='edit_subject'),
    path("delete/subject/<int:subject_id>", views.delete_subject, name='delete_subject'),
    path("subject/details/<int:subject_id>", views.subject_details, name='subject_details'),
    # path('subject_details/<int:subject_id>/pdf/', views.subject_details_pdf, name='subject_details_pdf'),
    path("add/teacher", views.add_teacher, name='add_teacher'),
   
    path("add/student", views.add_student,name="add_student"),
    path("student/edit/<int:student_id>",views.edit_student, name='edit_student'),
    path("student/delete/<int:student_id>",views.delete_student, name='delete_student'),
    path("manage/student/",views.manage_student,name='manage_student'),
    path("check_email", views.check_email, name="check_email"),
    path("manage/teacher/", views.manage_teacher, name='manage_teacher'),
    path("edit/teacher/<int:teacher_id>", views.edit_teacher, name='edit_teacher'),
    path("delete/teacher/<int:teacher_id>",views.delete_teacher, name='delete_teacher'),
    path("admin/profile", views.admin_profile, name='admin_profile'),
    path('add/book/', views.add_book, name='add_book'),
    path("edit/book/<int:book_id>", views.edit_book, name='edit_book'),
    path("delete/book/<int:book_id>", views.delete_book, name='delete_book'),
    path('view/book/',views.manage_book, name='manage_book'),
    path('view/notice/',views.notice_view, name='view_notice'),
    path('add/notice/',views.add_notice, name='add_notice'),
    path('edit/notice/<int:pk>',views.edit_notice, name='edit_notice'),
    path('delete/notice/<int:pk>',views.delete_notice, name='delete_notice'),
    path("view/leave/", views.view_leave, name="view_leave",),
    
]