from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='homepage'),
    path("login", views.login_page, name='loginpage'),
    path("Login/", views.Login, name='user_login'),
    path("Logout/", views.Logout, name='user_logout'),
    path("admin/home/", views.admin_home_page, name='admin_home_page'),
    path("add/class/", views.add_class, name='add_class'),
    path("manage/class/", views.manage_class, name='manage_class'),
    path("edit/class/<int:level_id>", views.edit_class, name='edit_class'),
    path("delete/class/<int:level_id>", views.delete_class, name='delete_class'),
    path("add/section/", views.add_section, name='add_section'),
    path("manage/section/", views.manage_section, name='manage_section'),
    path("edit/section/<int:section_id>", views.edit_section, name='edit_section'),
    path("delete/section/<int:section_id>", views.delete_section, name='delete_section'),
    path("add/session/", views.add_session, name='add_session'),
    path("manage/session/", views.manage_session, name='manage_session'),
    path("edit/session/<int:session_id>",views.edit_session, name='edit_session'),
    path("delete/session/<int:session_id>",views.delete_session, name='delete_session'),
    path("add/subject/",views.add_subject,name='add_subject'),
    path("manage/subject/", views.manage_subject, name='manage_subject'),
    path("edit/subject/<int:subject_id>", views.edit_subject, name='edit_subject'),
    path("delete/subject/<int:subject_id>", views.delete_subject, name='delete_subject'),
    path("subject/details/<int:subject_id>", views.subject_details, name='subject_details'),
    # path('subject_details/<int:subject_id>/pdf/', views.subject_details_pdf, name='subject_details_pdf'),
    path("add/teacher", views.add_teacher, name='add_teacher'),
    
    
    path('get_subjects/', views.get_subjects, name='get_subjects'),
    
    path('get_sections/', views.get_sections, name='get_sections'),
   
   
    path("assign/teacher/",views.assign_teacher,name='assign_teacher'),
    path("manage/assigned/teacher/", views.manage_assign_teacher, name='manage_assign_teacher'),
    path("edit/assign/teacher/<int:assignteacher_id>", views.edit_assign_teacher, name='edit_assign_teacher'),
    path("delete/assign/teacher/<int:assignteacher_id>", views.delete_assign_teacher, name='delete_assign_teacher'),
   
    path("add/student", views.add_student,name="add_student"),
    path("student/edit/<int:student_id>",views.edit_student, name='edit_student'),
    path("student/delete/<int:student_id>",views.delete_student, name='delete_student'),
    path("manage/student/",views.manage_student,name='manage_student'),
    path("check_email", views.check_email, name="check_email"),
    path("manage/teacher/", views.manage_teacher, name='manage_teacher'),
    path("edit/teacher/<int:teacher_id>", views.edit_teacher, name='edit_teacher'),
    path("delete/teacher/<int:teacher_id>",views.delete_teacher, name='delete_teacher'),
    path("admin/profile", views.admin_profile, name='admin_profile'),
    path('add/book/', views.add_book, name='add_book'),
    path("edit/book/<int:book_id>", views.edit_book, name='edit_book'),
    path("delete/book/<int:book_id>", views.delete_book, name='delete_book'),
    path('view/book/',views.manage_book, name='manage_book'),
    path('view/notice/',views.notice_view, name='view_notice'),
    path('add/notice/',views.add_notice, name='add_notice'),
    path('edit/notice/<int:pk>',views.edit_notice, name='edit_notice'),
    path('delete/notice/<int:pk>',views.delete_notice, name='delete_notice'),
    path("teacher/leave/", views.teacher_check_leave, name="teacher_check_leave"),
    path("student/leave/", views.student_check_leave, name="student_check_leave"),
    path('view/timetable/', views.view_timetable, name='view_timetable'),
    path('check/testimonial/', views.testimonial, name='testimonial'),
    path('add/home/', views.about_home, name='about_home'),
    path('manage/home/', views.manage_home_page, name='manage_home_page'),
    path('edit/home/<int:pk>',views.edit_home, name='edit_home'),
    path('delete/home/<int:pk>',views.delete_home, name='delete_home'),
    path('manage/about/', views.manage_about_page, name='manage_about_page'),
    path('add/about/', views.aboutpage_home, name='aboutpage_home'),
    path('edit/about/<int:pk>',views.edit_about, name='edit_about'),
    path('delete/about/<int:pk>',views.delete_about, name='delete_about'),
    
    path('add/bod/', views.bod_page, name='bod_page'),
    path('manage/bod/', views.manage_bod_page, name='manage_bod_page'),
    path('edit/bod/<int:pk>',views.edit_bod_page, name='edit_bod_page'),
    path('delete/bod/<int:pk>',views.delete_bod, name='delete_bod_page'),
    path('admin/attendance/session',views.admin_attendance_batch,name='admin_attendance_batch'),
    path('admin/view/attendance/<int:session_id>/', views.admin_view_attendance, name='admin_view_attendance'),
    path('admin/manage/attendance/section/<int:session_id>/<int:level_id>/', views.manage_attendance_section, name='manage_attendance_section'),
    path('admin/attendance/view/section/<int:session_id>/<int:level_id>/<int:section_id>',views.section_view_students_attendance,name='section_view_students_attendance'),
    path('admin/attendance/pdf/<int:session_id>/<int:student_id>',views.attendance_pdf,name='attendance_pdf'),
    path('admin/view/all/attendance/<int:session_id>/<int:section_id>',views.admin_view_all_attendance,name='admin_view_all_attendance'),
    path('admin/download/all/attendance/<int:session_id>/<int:section_id>',views.admin_download_all_attendance,name='admin_download_all_attendance'),
    path('admin/daily/download/all/attendance/<int:session_id>/<int:section_id>',views.daily_all_attendance_pdf,name='daily_all_attendance'),
    path('admin/weekly/download/all/attendance/<int:session_id>/<int:section_id>',views.weekly_all_attendance_pdf,name='weekly_all_attendance'),
    path('admin/yearly/download/all/attendance/<int:session_id>/<int:section_id>',views.yearly_all_attendance_pdf,name='yearly_all_attendance'),
    path('admin/view/student/attendance/<int:session_id>/<int:student_id>',views.admin_attendance_view,name='admin_attendance_view'),
    path('admin/view/daily/attendance/pdf/<int:session_id>/<int:student_id>',views.view_daily_attendance_pdf,name='view_daily_attendance_pdf'),
    path('admin/view/weekly/attendance/pdf/<int:session_id>/<int:student_id>',views.view_weekly_attendance_pdf,name='view_weekly_attendance_pdf'),
    path('admin/view/yearly/attendance/pdf/<int:session_id>/<int:student_id>',views.view_yearly_attendance_pdf,name='view_yearly_attendance_pdf'),
    
    
]