# Generated by Django 4.1.3 on 2023-01-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
