# Generated by Django 4.1.3 on 2023-02-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0004_alter_student_level_alter_student_section_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administratior.session'),
        ),
    ]
