# Generated by Django 4.1.3 on 2023-03-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(max_length=60),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default='', max_length=60),
        ),
    ]
