# Generated by Django 4.1.3 on 2023-04-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='NoteRoom',
        ),
    ]
