# Generated by Django 4.1.3 on 2023-02-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '__first__'),
        ('teacher', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administratior.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administratior.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administratior.student')),
            ],
        ),
    ]
