# Generated by Django 4.1.3 on 2023-01-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0004_timetable'),
        ('teacher', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administratior.subject'),
        ),
    ]
