# Generated by Django 4.1.3 on 2023-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.CharField(default='', max_length=60),
        ),
    ]
