# Generated by Django 4.1.3 on 2023-02-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
