# Generated by Django 4.1.3 on 2023-02-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_attendance_updated_date_attendance_upload_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
