# Generated by Django 4.1.3 on 2023-02-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '__first__'),
        ('teacher', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200)),
                ('select_level', models.CharField(choices=[('Easy', 'Easy'), ('Difficult', 'Difficult')], default='1', max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administratior.session')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administratior.subject')),
            ],
        ),
    ]
