# Generated by Django 4.1.3 on 2023-01-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0001_initial'),
        ('teacher', '0005_alter_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administratior.subject'),
        ),
    ]
