# Generated by Django 4.1.3 on 2023-01-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_question_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(max_length=200),
        ),
    ]
