# Generated by Django 4.1.3 on 2023-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Difficult', 'Difficult')], default='1', max_length=30),
        ),
    ]
