# Generated by Django 4.1.3 on 2023-01-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
