# Generated by Django 4.1.3 on 2023-02-28 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?[0-9]{8,16}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?[0-9]{8,16}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?[0-9]{8,16}$')]),
        ),
    ]
