# Generated by Django 4.1.3 on 2022-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
