# Generated by Django 4.1.3 on 2023-02-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0002_alter_section_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administratior.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administratior.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administratior.section'),
        ),
    ]
