# Generated by Django 4.1.3 on 2023-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0002_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
