# Generated by Django 4.1.3 on 2023-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0003_alter_student_fathers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mothers_number',
            field=models.IntegerField(null=True),
        ),
    ]
