# Generated by Django 4.1.3 on 2023-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0003_alter_newsandevents_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
    ]
