# Generated by Django 4.1.3 on 2023-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0004_alter_student_mothers_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.CharField(default='', max_length=12),
        ),
    ]
