# Generated by Django 4.1.3 on 2023-04-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0004_alter_newsandevents_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
