# Generated by Django 4.1.3 on 2023-01-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0005_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
