# Generated by Django 4.1.3 on 2023-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0006_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
    ]
