# Generated by Django 4.1.3 on 2023-01-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administratior.session'),
        ),
    ]
