# Generated by Django 4.1.3 on 2023-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratior', '0008_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fathers_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
