# Generated by Django 4.1.3 on 2023-03-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
